### ISSUE TITLE
Add new feature to ignore 404 errors

### ISSUE THREAD

**Issue by juth** [Agenty/public-roadmap#8]
Since some of the reports I need to scrape are returning 404 errors, it would be great to have a toggle under [Agent] > Configuration > Wait for that says, "Ignore 404 errors" or something like that.

**Comment by vickyRathee** [comment]
This feature has been released.

![image](https://user-images.githubusercontent.com/6106479/175814912-d16f2364-9605-4645-bf68-63436b1dc42a.png)

When enabled, the [web scraping](https://agenty.com/products/scraping-agent/) agent will wait even error status codes as well.
For example, here are the logs where 404 was returned by the website but the agent is still waiting for 5s to watch for h3.

![image](https://user-images.githubusercontent.com/6106479/175814975-c5388856-f3ee-42da-bc30-5ebc2cff314c.png)
